### ISSUE TITLE
Conflict between OTG and Fossil mod

### ISSUE THREAD

**Issue by RodrigoTaipe93** [Darsenia/Traveler-s-Dream#3] opened 2020-04-03 19:02 UTC
Hello, Darsenia!

Sorry to bother you, there seems to be an issue between OTG and the Fossil mod. I was wondering if Traveler's Dream was also involved.

I leave the link to the original thread:

- https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1714#issuecomment-608565894

**Comment by Darsenia** [comment] 2020-04-03 21:38
Hello,
This is actually not an issue, cause id conflicts may sometimes happen if installed mods have too many biomes.In OTG v8+ biomes ids are also dynamic, so if such an issue appers, it may be not enough free biome ids.For example Biomes O'Plenty cannot generate it's biomes in OTG world,by still takes more than a hundreed of biome ids.I recommend not to install such mods with OTG presets like TD.

Also, **Serene Seasons** seems to be incompatible with Traveler's Dream:seasons cause ice in ice zone melt,that is not good.I need to add this information to my curse page....

**JustEnoughIds is incompatible with OTG.It will not help at all.**

 Anyway,thank you for this issue post, cause you managed to find forgotten feature in Traveler's Dream,that wasn't fully removed!My bad=)I will fix this in the next release as soon as it will be ready.
(Ice Volcano was removed from worldgen, but its files were recognised by OTG automatically and appeared in ids list....)

**You can try now to do this:**

**1)**Find OpenTerrainGenerator folder in mods folder.Find there Traveler'sDreamCompact folder.Open WorldBiomes folder and delete every file named like "Ice Volcano"(Ice Volcano.Ice Volcano Pit and Ice Volcano Edge).After that open WorldConfig.ini file with Notepad (++ or Kate or other text program) and find there those IceVolcano Related names in Biome Lists and remove them.Be careful with "," symbols.
If you do everything properly, Ice Volcano will dissapear from Ids list.

**2)**I still think that you may have no free ids.Dump with TellMe mod biomes and you will see if this is true.

**Comment by Darsenia** [comment] 2020-04-03 21:47
! Firstly remove JustEnoughIds : this may be enough. JEID does strange things. Don't forget to make new world after that.

**Comment by RodrigoTaipe93** [comment] 2020-04-03 22:30
Ok, so I have a lot of question.

1. What does exactly does JEIDs then? In their description they pointed out that they removed the ID limit on biomes and other features? So were they wrong?

2. What happens when Serene Seasons and TD combine then? Until now, the world looked fine to me

Does your mod offer the same mechanics as Serene Seasons? (talking about Traveler's Dream:seasons)

3. I disabled the biomes of Biomes O'Plenty since I just want the flora. Even then, the biomes take space? (the IDs)

There was a guy that published another OTG mod that claimed to be compatible with Biomes O'Plenty? Is he wrong?

- https://www.curseforge.com/minecraft/mc-mods/far-from-home

Sorry for so many question, but building a private modpack with stable mods seem to be a wishful thinking nowadays :(

**Comment by Darsenia** [comment] 2020-04-04 12:55
That's normal, I have been making private modpacks ...since minecraft 1.2.5, as I remember :-D I know that's painful sometimes.

**Firstly,again, please remove JEID and test :  if I didn't miss something in your crash report mod list, you should still have at about 20 free biome ids!**
You have these mods with biomes : TD,Biomes O'Plenty,Betweenlands,AetherII, Better Nether,NetherEx. 
Your modpack should work good.
(very beautiful modpack, but performance-eating)

Now answers:

1) JEID is intended to remove biomes ids limit, but it isn't working with OTG.It was confirmed multiple times by different people with different presets.That was written in my post in Compatibility section.

2)Serene Seasons affects temperature of biomes, so IceZone biomes start melting.Big ice things are turning into waterfalls very quickly.That was unpredictable nonsense for me,I didin't know that seasons can affect such cold arctic zones, but it happens.

You can still use Serene Seasons, if you don't mind living in Ice Zone.

I didn't mean TravelersDream:seasons,I meant seasons from Serene Seasons mod=)Sorry for my English.Traveler's Dream isn't a mod,it's a preset for OTG.So it doesn't add any stuff or new mechanics ingame.It is like...changing and creating config text files and using similar to schematic objects with them.No code, just objects and numbers.

3)Disabling Biomes O'Plenty biomes = disabling their generation in your world.Ids will still remain=)
Not that easy...

Traveler's Dream Compact can still be used with BiomesO'Plenty (you will have at about 40 free ids after installing BOP), but if you also install several big mods with many-many biomes, your ids could run out of limit.

Id limit is 256 (0-255)

Far From Home also doesn't offer Biomes O'Plenty biomes spawn in overworld.It uses BOP blocks(wood,leaves,plants etc) for generation.Biomes O'Plenty still will register it's ids in the game.

I hope I was helpful enough=)

**Comment by Darsenia** [comment] 2020-04-15 14:12
EDIT:
I 'm sorry but I was wrong about BOP ids.Now they seem to be fully disabling through the config file.
Things change=)
Also, cause this issue haven't got any responses or activity for a long time, I will have to close it.

**Closed as completed by Darsenia** 2020-04-15 14:12 UTC
