### ISSUE TITLE
Crash on World Generation

### ISSUE THREAD

**Issue by TwoBoogerFace** [Darsenia/Traveler-s-Dream#2] opened 2019-12-20 00:30 UTC
On a new world generation, I get an error as follows:

>  The game crashed whilst exception in server tick loop
Error: java.lang.RuntimeException: Error: Biome "Red Maple Border1" has an id between 0-255 but uses replaceToBiomeName. Virtual biomes must have id's above 255, please check your WorldConfig's custom biomes setting.

I can give you the entire log if you need it. I do have about 200-300 extra biomes, plus Vanilla, plus this. To do this, I have a mod called "JustEnoughIDs" which extends ID caps, including biomes, by using 1.13 chunk format. I don't know much detailed information, but when a world is loaded with this mod loaded, it changes from a 1.12.2 world, to a 1.13-JEID world, which may mean something.

With this mod, it adjusts all of the biome IDs, which I have observed with the Biome Paint Tool from the Biome Paint Tools mod. I've noticed that the biomes added in this mod, or items, do not appear in the Creative Inventory or Just Enough Items, which I do not know if that is a feature or not, or if the mod's items only appear in the Traveler's Dream setting.

Now, my game crashed on world creation using Create OTG World. I tried to find a "WorldConfig" file, but I couldn't find it in the "saves" folder or the "config" folder.

**Comment by Darsenia** [comment] 2019-12-20 21:21
Hello,
Firstly,I also tried to use jeid with OTG before with my preset and that do not work.I read similar issues on OTG issues page about other OTG  preset(Far From Home, if I remember right,that is not important).It seems that JEID do not work with OTG.Do not waste your time on tricks,it seems to be no way to have more than mentioned in the post amount of other mods biomes(40+).Unfortunately.Also other mods biomes will not appear in the world,so you have no reason to install other biome mod together with this preset.
Secondly,Traveler's Dream is not a mod,it is just a preset for OTG.So it doesn't add any items or blocks.Besides biomes,it is a completely vanilla thing.Biomes here work a bit differently than in other mods too.Configs here are very complicated for the user,who is not familiar with how OTG works.You will not be able to change something about biomes without heavy consequences,if you do not know exactly how the preset is made.It is similar to interruption into the mod code in some way.

**Comment by Darsenia** [comment] 2019-12-20 21:31
1.13 or higher release of OTG will fix the issue with biome id limit,when it will be released.

**Comment by TwoBoogerFace** [comment] 2019-12-21 04:12
Thanks for telling me this. I would love to use this mod, but I love biome mods, and this would not work well with me. May I suggest a smaller version of this mod which is compatible with other mods, maybe with less biomes? I think the mod is somewhat hard to play with because of the fact it can't play with other mods well.

**Comment by Darsenia** [comment] 2019-12-21 12:18
I know.I love biome mods too, but there is no practical need in them-they will not spawn at all with OTG preset.The only thing that I personally miss - blocks, BOP woods and vegetation for example.I'm currently working on something big,that will help TD to use less biome ids and will add a lot of  wood,decoration things,flowers etc to the generation.It will probably compensate the inability to use other biome mods.
Maybe if I make more biomes virtual,it will help,but there will a giant loss of biomes special colors,climate and even forge dictionary tags.It may ruin other mods mobs spawning.For example I had to use a separate id for a mountain to leave its "MOUNTAIN" tag, even if it has the same colors as a forest.The snow on a top also depends on a temperature, changing top biome to virtual will ruin it :( 
Make a smaller version...I can't just cut out the part of the mod and throw it away:)
But when my current plans will be finished, I want to make another preset with much less used biomes ids, but also beautiful.But I have only two hands  and 24 hours in a day ;-D

**Comment by Darsenia** [comment] 2019-12-23 10:34
"Mods that change terrain generation like Realistic Terrain Generation/Alternate Terrain Generation/Biomes O` Plenty will either not work or crash." -from the OTG wiki.OTG was designed as an alternative to biome mods.It is not intended to work together with them.
I try to make cut-edition with less biome ids used as soon as possible,but it will be different visually.

**Closed as completed by Darsenia** 2019-12-23 10:34 UTC
